[package]
name = "hgraphs"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
description = "Hypergraph algorithms and data structures for HGraphs.jl"
keywords = ["hypergraphs", "data-structures"]
readme = false

[lints]
workspace = true

[dependencies]
hgraphs-core.workspace = true
petgraph.workspace = true

[dev-dependencies]
rustworkx-core.workspace = true
