[package]
name = "hgraphs-core"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
description = "Core traits for hypergraph data structures and algorithms"
keywords = ["hypergraphs", "data-structures"]
readme = false

[features]
default = ["alloc"]
alloc = []

[lints]
workspace = true
